### ISSUE TITLE
Move code repository to OSGeo?

### ISSUE THREAD

**Issue by desruisseaux** [OSGeo/PROJ-JNI#41]
(Following on #33) The https://github.com/Kortforsyningen/ home was intended to be temporary. Should we move the repository to https://github.com/OSGeo/ group? There would be no history lost if we use Settings / Transfer ownership.

Together with such transform, package `org.kortforsyningen.proj` could be renamed `org.osgeo.proj`.

**Comment by kbevers** [comment]
With the adoption as a community member this should be fine. I should be able to transfer the repository. Should we coordinate that with a PR that changes the package name to `org.osgeo.proj`? Also, do we have anything set up that might break in the process?

**Comment by desruisseaux** [comment]
I do not know for Travis, but everything else should be fine if we do a "search and replace" from `kortforsyningen` to `osgeo` together with directories renaming. I can try to do a pull request for that in the next few days. But I guess it is okay to do the transfer of ownership before the renaming.

**Comment by kbevers** [comment]
Travis was just removed: https://github.com/Kortforsyningen/PROJ-JNI/pull/43. 

> But I guess it is okay to do the transfer of ownership before the renaming.

Yeah, that shouldn't be a big issue. I'll start the transfer right away.
