### ISSUE TITLE
Rename "master" as "main"?

### ISSUE THREAD

**Issue by desruisseaux** [OSGeo/PROJ-JNI#55]
Should we rename the `master` branch has `main`? The procedure is [described here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) and seems simple:

**Comment by desruisseaux** [comment]
Having hear no objection in one week, I will proceed.

**Comment by desruisseaux** [comment]
Apparently I do not have administrator right for doing this operation. If someone with more power is willing to do the renaming, it should take only one minute (click on the pen on the right side of "master" [on this page](https://github.com/OSGeo/PROJ-JNI/branches)).

**Comment by kbevers** [comment]
@desruisseaux you've now got admin rights to this repository. Please fix it yourself and remember that with great power comes great responsibility :-)

**Comment by desruisseaux** [comment]
Thanks, renaming applied. Local clones can update as below (copied from GitHub instructions):

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
