### ISSUE TITLE
Wrong arguments for equals()

### ISSUE THREAD

**Issue by ggmuelle** [OSGeo/PROJ-JNI#71]
In https://github.com/OSGeo/PROJ-JNI/blob/1e06ea8225bc0355bbbe8030fdbb4e8010c80469/src/main/java/org/osgeo/proj/SimpleDirectPosition.java#L141 a CRS is compared to a boolean. I guess it needs to be like this:

return Objects.equals(crs, other.getCoordinateReferenceSystem())

**Comment by desruisseaux** [comment]
Indeed, thanks for spotting that! I just pushed the fix.
