### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by nirolevy** [OSGeo/PROJ-JNI#72]
Hi,
I'm trying to use PROJ-JNI with Spark, and am getting OOM errors
I was able to reproduce with this simple code:
```java
    public static void main(String[] args)  throws FactoryException, InterruptedException{
        for (int i = 0; i < 10000000; i++) {
            MathTransform mt = (MathTransform) Proj.createFromUserInput("urn:ogc:coordinateOperation:EPSG::1740");
            System.out.println(i + ": " + mt.toWKT().length());
        }
    }
```
that memory signature very quickly grows to over 20GB

I have also noticed that in CleanerFactory, `queue.remove` (line 95) never returns... It seems to me that the references are registered on another `ReferenceQueue`

Unfortunately, having never worked with JNI, I'm a bit lost here... Does anyone have any idea how can I further debug this?

**Comment by desruisseaux** [comment]
Hello. Thanks for the bug report. I will try to take a look later this week when I have a chance.

**Comment by desruisseaux** [comment]
Hello @nirolevy. I'm closing this issue since it does not seem to be a PROJ-JNI issue. But let us know if it is not the case and this issue needs to be reopened.
